version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    image: message-app
    container_name: message-app
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - 5173:5173
    depends_on:
      - db
    volumes:
      - ./:/var/www
    networks:
      - message

  db:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: message-db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - message
    volumes:
      - message:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: message-nginx
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./:/var/www
      - ./docker/nginx/${NGINX_CONF_NAME}:/etc/nginx/conf.d/default.conf
    networks:
      - message

  mailhog:
    image: mailhog/mailhog
    container_name: message-mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - message

volumes:
  message:

networks:
  message:
    driver: bridge
